package com.csc.fsg.life.pw.io.descriptor.wma;

import com.csc.fsg.life.pw.io.*;

public class T066XDescriptor
    extends TableDescriptor
{
    private static final String pagingSql = "SELECT COMPANY_CODE, PRODUCT_PREFIX, TABLE_SUBSET, EFFECTIVE_DATE, SEX_CODE, SPECIAL_CLASS_CODE, PREMIUM_CLASS_CODE, MAX_AGE, MAX_DURATION, BEGIN_DURATION, END_DURATION, MAX_FACE_AMOUNT, CSH_VAL_PER_THOUS FROM ";
    
    public void initialize()
    {
        setRowClass(T066XRow.class);
        setTableName("T066X");
        setTableId("066");
        super.initialize();
    }
    
    public void initializeColumnDescriptors()
    {
        super.initializeColumnDescriptors();
        addColumnDescriptor(new ColumnDescriptor(this,"getCompanyCode","setCompanyCode","COMPANY_CODE,1,1,3,0,true|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getProductPrefix","setProductPrefix","PRODUCT_PREFIX,1,2,1,0,true|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getTableSubset","setTableSubset","TABLE_SUBSET,1,3,16,0,true|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getEffectiveDate","setEffectiveDate","EFFECTIVE_DATE,91,4,10,0,true|T,0,DATE,0,null,null,null,null,null|U,0,DATE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getSexCode","setSexCode","SEX_CODE,1,5,1,0,true|T,0,CHAR,0,null,null,null,null,null|U,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getSpecialClassCode","setSpecialClassCode","SPECIAL_CLASS_CODE,1,6,2,0,true|T,0,CHAR,0,null,null,null,null,null|U,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPremiumClassCode","setPremiumClassCode","PREMIUM_CLASS_CODE,1,7,1,0,true|T,0,CHAR,0,null,null,null,null,null|U,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxAge","setMaxAge","MAX_AGE,3,8,3,0,true|T,0,INTEGER,0,null,null,null,null,null|U,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxDuration","setMaxDuration","MAX_DURATION,3,9,3,0,true|T,0,INTEGER,0,null,null,null,null,null|U,0,INTEGER,2,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getBeginDuration","setBeginDuration","BEGIN_DURATION,3,10,3,0,true|T,0,INTEGER,2,null,null,null,null,null|U,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getEndDuration","setEndDuration","END_DURATION,3,11,3,0,true|T,0,INTEGER,2,null,null,null,null,null|U,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxFaceAmount","setMaxFaceAmount","MAX_FACE_AMOUNT,3,12,8,0,true|T,0,INTEGER,0,null,null,null,null,null|U,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getCshValPerThous","setCshValPerThous","CSH_VAL_PER_THOUS,3,13,8,4,false|T,0,DOUBLE,0,null,null,null,null,null|U,0,DOUBLE,0,null,null,null,null,null"));
    }
    
    public String getPagingSQL(String schemaName,boolean isSubsetMode,boolean isNext, boolean locator)
    {
        String pagingWhere = null;
        String order = null;
        if (isNext) {
            if (isSubsetMode)
                if (locator)
                    pagingWhere = ".T066X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE > :effective_date) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE > :max_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION > :max_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION > :begin_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION > :end_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT > :max_face_amount) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT = :max_face_amount)) ";
                else 
                    pagingWhere = ".T066X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE > :effective_date) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE > :max_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION > :max_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION > :begin_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION > :end_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT > :max_face_amount)) ";
            else
                if (locator)
                    pagingWhere = ".T066X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX > :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET > :table_subset) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE > :max_age) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION > :max_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION > :begin_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION > :end_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT > :max_face_amount) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT = :max_face_amount)) ";
                else
                    pagingWhere = ".T066X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX > :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET > :table_subset) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE > :max_age) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION > :max_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION > :begin_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION > :end_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT > :max_face_amount)) ";
            order = " ORDER BY COMPANY_CODE, PRODUCT_PREFIX, TABLE_SUBSET, EFFECTIVE_DATE, SEX_CODE, SPECIAL_CLASS_CODE, PREMIUM_CLASS_CODE, MAX_AGE, MAX_DURATION, BEGIN_DURATION, END_DURATION, MAX_FACE_AMOUNT";
        }
        else {
            if (isSubsetMode)
                pagingWhere = ".T066X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE < :effective_date) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE < :sex_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE < :special_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE < :premium_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE < :max_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION < :max_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION < :begin_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION < :end_duration) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT < :max_face_amount)) ";
            else
                pagingWhere = ".T066X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX < :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET < :table_subset) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE < :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE < :sex_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE < :special_class_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE < :premium_class_code) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE < :max_age) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION < :max_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION < :begin_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION < :end_duration) OR (PRODUCT_PREFIX = :product_prefix AND TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_AGE = :max_age AND MAX_DURATION = :max_duration AND BEGIN_DURATION = :begin_duration AND END_DURATION = :end_duration AND MAX_FACE_AMOUNT < :max_face_amount)) ";
            order = " ORDER BY COMPANY_CODE DESC, PRODUCT_PREFIX DESC, TABLE_SUBSET DESC, EFFECTIVE_DATE DESC, SEX_CODE DESC, SPECIAL_CLASS_CODE DESC, PREMIUM_CLASS_CODE DESC, MAX_AGE DESC, MAX_DURATION DESC, BEGIN_DURATION DESC, END_DURATION DESC, MAX_FACE_AMOUNT DESC";
        }
        return pagingSql + schemaName + pagingWhere + order;
    }
    
    public String prepareInsertStmt(String schemaName) {
        StringBuffer sb = new StringBuffer();
        sb.append("INSERT INTO ").append(schemaName);
        sb.append(".T066X ( ");
        sb.append("COMPANY_CODE, PRODUCT_PREFIX, TABLE_SUBSET, EFFECTIVE_DATE, SEX_CODE, SPECIAL_CLASS_CODE, PREMIUM_CLASS_CODE, MAX_AGE, MAX_DURATION, BEGIN_DURATION, END_DURATION, MAX_FACE_AMOUNT, CSH_VAL_PER_THOUS )");
        sb.append(" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )");
        return sb.toString();
    }
    
    public String prepareUpdateStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("UPDATE ").append(schemaName);
        sb.append(".T066X ");
        sb.append(" SET COMPANY_CODE = ?, PRODUCT_PREFIX = ?, TABLE_SUBSET = ?, EFFECTIVE_DATE = ?, SEX_CODE = ?, SPECIAL_CLASS_CODE = ?, PREMIUM_CLASS_CODE = ?, MAX_AGE = ?, MAX_DURATION = ?, BEGIN_DURATION = ?, END_DURATION = ?, MAX_FACE_AMOUNT = ?, CSH_VAL_PER_THOUS = ?");
        sb.append(" WHERE COMPANY_CODE = ? AND PRODUCT_PREFIX = ? AND TABLE_SUBSET = ? AND EFFECTIVE_DATE = ? AND SEX_CODE = ? AND SPECIAL_CLASS_CODE = ? AND PREMIUM_CLASS_CODE = ? AND MAX_AGE = ? AND MAX_DURATION = ? AND BEGIN_DURATION = ? AND END_DURATION = ? AND MAX_FACE_AMOUNT = ?");
        return sb.toString();
    }
    
    public String prepareDeleteStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("DELETE FROM ").append(schemaName);
        sb.append(".T066X ");
        sb.append(" WHERE COMPANY_CODE = ? AND PRODUCT_PREFIX = ? AND TABLE_SUBSET = ? AND EFFECTIVE_DATE = ? AND SEX_CODE = ? AND SPECIAL_CLASS_CODE = ? AND PREMIUM_CLASS_CODE = ? AND MAX_AGE = ? AND MAX_DURATION = ? AND BEGIN_DURATION = ? AND END_DURATION = ? AND MAX_FACE_AMOUNT = ?");
        return sb.toString();
    }
}
