package com.csc.fsg.life.pw.web.io.descriptor.wma;

import com.csc.fsg.life.pw.web.io.*;

public class T000XDescriptor
    extends TableDescriptor
{
    private static final String pagingSql = "SELECT COMPANY_CODE, PRODUCT_PREFIX, PRODUCT_SUFFIX, PLAN_CODE, ISSUE_STATE, LINE_OF_BUSINESS, EFFECTIVE_DATE, PLAN_TYPE, TABLE_PTR_ID, TABLE_PTR_VAR, TABLE_PTR_SUBSET FROM ";
    
    public void initialize()
    {
        setRowClass(PlanRow.class);
        setTableName("T000X");
        setTableId("000");
        super.initialize();
    }
    
    public void initializeColumnDescriptors()
    {
        super.initializeColumnDescriptors();
        addColumnDescriptor(new ColumnDescriptor(this,"getCompanyCode","setCompanyCode","COMPANY_CODE,1,1,3,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getProductPrefix","setProductPrefix","PRODUCT_PREFIX,1,2,1,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getProductSuffix","setProductSuffix","PRODUCT_SUFFIX,1,3,1,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPlanCode","setPlanCode","PLAN_CODE,1,4,6,0,true|A,0,CHAR,0,null,null,null,null,null|H,0,CHAR,0,null,null,null,null,null|N,0,CHAR,0,null,null,null,null,null|T,0,CHAR,0,null,null,null,null,null|U,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getIssueState","setIssueState","ISSUE_STATE,1,5,3,0,true|A,0,CHAR,0,null,null,null,null,null|H,0,CHAR,0,null,null,null,null,null|N,0,CHAR,0,null,null,null,null,null|T,0,CHAR,0,null,null,null,null,null|U,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLineOfBusiness","setLineOfBusiness","LINE_OF_BUSINESS,1,6,3,0,true|A,0,CHAR,0,null,null,null,null,null|H,0,CHAR,0,null,null,null,null,null|N,0,CHAR,0,null,null,null,null,null|T,0,CHAR,0,null,null,null,null,null|U,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getEffectiveDate","setEffectiveDate","EFFECTIVE_DATE,91,7,10,0,true|A,0,DATE,0,null,null,null,null,null|H,0,DATE,0,null,null,null,null,null|N,0,DATE,0,null,null,null,null,null|T,0,DATE,0,null,null,null,null,null|U,0,DATE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPlanType","setPlanType","PLAN_TYPE,1,8,1,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getTablePtrId","setTablePtrId","TABLE_PTR_ID,1,9,3,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getTablePtrVar","setTablePtrVar","TABLE_PTR_VAR,1,10,1,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getTablePtrSubset","setTablePtrSubset","TABLE_PTR_SUBSET,1,11,16,0,true|A,0,CHAR,1,null,null,null,null,null|H,0,CHAR,1,null,null,null,null,null|N,0,CHAR,1,null,null,null,null,null|T,0,CHAR,1,null,null,null,null,null|U,0,CHAR,1,null,null,null,null,null"));
    }
    
    public String getPagingSQL(String schemaName,boolean isSubsetMode,boolean isNext, boolean locator)
    {
        String pagingWhere = null;
        String order = null;
        if (isNext) {
            if (isSubsetMode)
                if (locator)
                    pagingWhere = ".T000X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND ((PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE > :plan_type) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID > :table_ptr_id) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR > :table_ptr_var) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET > :table_ptr_subset) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET = :table_ptr_subset)) ";
                else 
                    pagingWhere = ".T000X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND ((PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE > :plan_type) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID > :table_ptr_id) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR > :table_ptr_var) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET > :table_ptr_subset)) ";
            else
                if (locator)
                    pagingWhere = ".T000X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX > :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE > :plan_type) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID > :table_ptr_id) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR > :table_ptr_var) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET > :table_ptr_subset) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET = :table_ptr_subset)) ";
                else
                    pagingWhere = ".T000X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX > :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE > :plan_type) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID > :table_ptr_id) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR > :table_ptr_var) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET > :table_ptr_subset)) ";
            order = " ORDER BY COMPANY_CODE, PRODUCT_PREFIX, PRODUCT_SUFFIX, PLAN_CODE, ISSUE_STATE, LINE_OF_BUSINESS, EFFECTIVE_DATE, PLAN_TYPE, TABLE_PTR_ID, TABLE_PTR_VAR, TABLE_PTR_SUBSET";
        }
        else {
            if (isSubsetMode)
                pagingWhere = ".T000X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND ((PRODUCT_SUFFIX < :product_suffix) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE < :plan_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE < :issue_state) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS < :line_of_business) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE < :effective_date) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE < :plan_type) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID < :table_ptr_id) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR < :table_ptr_var) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET < :table_ptr_subset)) ";
            else
                pagingWhere = ".T000X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX < :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX < :product_suffix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE < :plan_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE < :issue_state) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS < :line_of_business) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE < :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE < :plan_type) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID < :table_ptr_id) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR < :table_ptr_var) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND PLAN_TYPE = :plan_type AND TABLE_PTR_ID = :table_ptr_id AND TABLE_PTR_VAR = :table_ptr_var AND TABLE_PTR_SUBSET < :table_ptr_subset)) ";
            order = " ORDER BY COMPANY_CODE DESC, PRODUCT_PREFIX DESC, PRODUCT_SUFFIX DESC, PLAN_CODE DESC, ISSUE_STATE DESC, LINE_OF_BUSINESS DESC, EFFECTIVE_DATE DESC, PLAN_TYPE DESC, TABLE_PTR_ID DESC, TABLE_PTR_VAR DESC, TABLE_PTR_SUBSET DESC";
        }
        return pagingSql + schemaName + pagingWhere + order;
    }
    
    public String prepareInsertStmt(String schemaName) {
        StringBuffer sb = new StringBuffer();
        sb.append("INSERT INTO ").append(schemaName);
        sb.append(".T000X ( ");
        sb.append("COMPANY_CODE, PRODUCT_PREFIX, PRODUCT_SUFFIX, PLAN_CODE, ISSUE_STATE, LINE_OF_BUSINESS, EFFECTIVE_DATE, PLAN_TYPE, TABLE_PTR_ID, TABLE_PTR_VAR, TABLE_PTR_SUBSET )");
        sb.append(" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )");
        return sb.toString();
    }
    
    public String prepareUpdateStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("UPDATE ").append(schemaName);
        sb.append(".T000X ");
        sb.append(" SET COMPANY_CODE = ?, PRODUCT_PREFIX = ?, PRODUCT_SUFFIX = ?, PLAN_CODE = ?, ISSUE_STATE = ?, LINE_OF_BUSINESS = ?, EFFECTIVE_DATE = ?, PLAN_TYPE = ?, TABLE_PTR_ID = ?, TABLE_PTR_VAR = ?, TABLE_PTR_SUBSET = ?");
        sb.append(" WHERE COMPANY_CODE = ? AND PRODUCT_PREFIX = ? AND PRODUCT_SUFFIX = ? AND PLAN_CODE = ? AND ISSUE_STATE = ? AND LINE_OF_BUSINESS = ? AND EFFECTIVE_DATE = ? AND PLAN_TYPE = ? AND TABLE_PTR_ID = ? AND TABLE_PTR_VAR = ? AND TABLE_PTR_SUBSET = ?");
        return sb.toString();
    }
    
    public String prepareDeleteStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("DELETE FROM ").append(schemaName);
        sb.append(".T000X ");
        sb.append(" WHERE COMPANY_CODE = ? AND PRODUCT_PREFIX = ? AND PRODUCT_SUFFIX = ? AND PLAN_CODE = ? AND ISSUE_STATE = ? AND LINE_OF_BUSINESS = ? AND EFFECTIVE_DATE = ? AND PLAN_TYPE = ? AND TABLE_PTR_ID = ? AND TABLE_PTR_VAR = ? AND TABLE_PTR_SUBSET = ?");
        return sb.toString();
    }
}
