package com.csc.fsg.life.pw.web.io.descriptor.wma;

import com.csc.fsg.life.pw.web.io.*;

public class T031EDescriptor
    extends TableDescriptor
{
    private static final String pagingSql = "SELECT COMPANY_CODE, TABLE_SUBSET, EFFECTIVE_DATE, POL_INCREASE_CODE, SEX_CODE, UNDER_BASIS_CODE, SPECIAL_CLASS_CODE, MAX_ISSUE_AGE, MAX_DURATION, MAX_ATTAINED_AGE, MAX_COVERAGE_UNITS, NO_LAPSE_IND, FLAT_FEE, CHG_PER_UNIT_COV, PCT_COST_OF_RISK, CONTAGION_FACTOR FROM ";
    
    public void initialize()
    {
        setRowClass(T031ERow.class);
        setTableName("T031E");
        setTableId("031");
        super.initialize();
    }
    
    public void initializeColumnDescriptors()
    {
        super.initializeColumnDescriptors();
        addColumnDescriptor(new ColumnDescriptor(this,"getCompanyCode","setCompanyCode","COMPANY_CODE,1,1,3,0,true|,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getTableSubset","setTableSubset","TABLE_SUBSET,1,2,16,0,true|,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getEffectiveDate","setEffectiveDate","EFFECTIVE_DATE,91,3,10,0,true|,0,DATE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPolIncreaseCode","setPolIncreaseCode","POL_INCREASE_CODE,1,4,1,0,true|,0,CHAR,4,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getSexCode","setSexCode","SEX_CODE,1,5,1,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnderBasisCode","setUnderBasisCode","UNDER_BASIS_CODE,1,6,1,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getSpecialClassCode","setSpecialClassCode","SPECIAL_CLASS_CODE,1,7,2,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxIssueAge","setMaxIssueAge","MAX_ISSUE_AGE,3,8,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxDuration","setMaxDuration","MAX_DURATION,3,9,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxAttainedAge","setMaxAttainedAge","MAX_ATTAINED_AGE,3,10,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxCoverageUnits","setMaxCoverageUnits","MAX_COVERAGE_UNITS,3,11,11,5,true|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getNoLapseInd","setNoLapseInd","NO_LAPSE_IND,1,12,1,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFlatFee","setFlatFee","FLAT_FEE,3,13,7,2,false|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getChgPerUnitCov","setChgPerUnitCov","CHG_PER_UNIT_COV,3,14,8,5,false|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPctCostOfRisk","setPctCostOfRisk","PCT_COST_OF_RISK,3,15,5,2,false|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getContagionFactor","setContagionFactor","CONTAGION_FACTOR,3,16,8,5,false|,0,DOUBLE,0,null,null,null,null,null"));
    }
    
    public String getPagingSQL(String schemaName,boolean isSubsetMode,boolean isNext, boolean locator)
    {
        String pagingWhere = null;
        String order = null;
        if (isNext) {
            if (isSubsetMode)
                if (locator)
                    pagingWhere = ".T031E WHERE (COMPANY_CODE = :company_code) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE > :effective_date) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE > :pol_increase_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE > :sex_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE > :under_basis_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE > :max_issue_age) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION > :max_duration) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE > :max_attained_age) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS > :max_coverage_units) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND > :no_lapse_ind) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND = :no_lapse_ind)) ";
                else 
                    pagingWhere = ".T031E WHERE (COMPANY_CODE = :company_code) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE > :effective_date) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE > :pol_increase_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE > :sex_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE > :under_basis_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE > :max_issue_age) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION > :max_duration) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE > :max_attained_age) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS > :max_coverage_units) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND > :no_lapse_ind)) ";
            else
                if (locator)
                    pagingWhere = ".T031E WHERE (COMPANY_CODE = :company_code) AND ((TABLE_SUBSET > :table_subset) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE > :effective_date) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE > :pol_increase_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE > :sex_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE > :under_basis_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE > :max_issue_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION > :max_duration) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE > :max_attained_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS > :max_coverage_units) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND > :no_lapse_ind) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND = :no_lapse_ind)) ";
                else
                    pagingWhere = ".T031E WHERE (COMPANY_CODE = :company_code) AND ((TABLE_SUBSET > :table_subset) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE > :effective_date) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE > :pol_increase_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE > :sex_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE > :under_basis_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE > :special_class_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE > :max_issue_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION > :max_duration) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE > :max_attained_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS > :max_coverage_units) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND > :no_lapse_ind)) ";
            order = " ORDER BY COMPANY_CODE, TABLE_SUBSET, EFFECTIVE_DATE, POL_INCREASE_CODE, SEX_CODE, UNDER_BASIS_CODE, SPECIAL_CLASS_CODE, MAX_ISSUE_AGE, MAX_DURATION, MAX_ATTAINED_AGE, MAX_COVERAGE_UNITS, NO_LAPSE_IND";
        }
        else {
            if (isSubsetMode)
                pagingWhere = ".T031E WHERE (COMPANY_CODE = :company_code) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE < :effective_date) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE < :pol_increase_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE < :sex_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE < :under_basis_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE < :special_class_code) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE < :max_issue_age) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION < :max_duration) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE < :max_attained_age) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS < :max_coverage_units) OR (EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND < :no_lapse_ind)) ";
            else
                pagingWhere = ".T031E WHERE (COMPANY_CODE = :company_code) AND ((TABLE_SUBSET < :table_subset) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE < :effective_date) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE < :pol_increase_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE < :sex_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE < :under_basis_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE < :special_class_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE < :max_issue_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION < :max_duration) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE < :max_attained_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS < :max_coverage_units) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND POL_INCREASE_CODE = :pol_increase_code AND SEX_CODE = :sex_code AND UNDER_BASIS_CODE = :under_basis_code AND SPECIAL_CLASS_CODE = :special_class_code AND MAX_ISSUE_AGE = :max_issue_age AND MAX_DURATION = :max_duration AND MAX_ATTAINED_AGE = :max_attained_age AND MAX_COVERAGE_UNITS = :max_coverage_units AND NO_LAPSE_IND < :no_lapse_ind)) ";
            order = " ORDER BY COMPANY_CODE DESC, TABLE_SUBSET DESC, EFFECTIVE_DATE DESC, POL_INCREASE_CODE DESC, SEX_CODE DESC, UNDER_BASIS_CODE DESC, SPECIAL_CLASS_CODE DESC, MAX_ISSUE_AGE DESC, MAX_DURATION DESC, MAX_ATTAINED_AGE DESC, MAX_COVERAGE_UNITS DESC, NO_LAPSE_IND DESC";
        }
        return pagingSql + schemaName + pagingWhere + order;
    }
    
    public String prepareInsertStmt(String schemaName) {
        StringBuffer sb = new StringBuffer();
        sb.append("INSERT INTO ").append(schemaName);
        sb.append(".T031E ( ");
        sb.append("COMPANY_CODE, TABLE_SUBSET, EFFECTIVE_DATE, POL_INCREASE_CODE, SEX_CODE, UNDER_BASIS_CODE, SPECIAL_CLASS_CODE, MAX_ISSUE_AGE, MAX_DURATION, MAX_ATTAINED_AGE, MAX_COVERAGE_UNITS, NO_LAPSE_IND, FLAT_FEE, CHG_PER_UNIT_COV, PCT_COST_OF_RISK, CONTAGION_FACTOR )");
        sb.append(" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )");
        return sb.toString();
    }
    
    public String prepareUpdateStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("UPDATE ").append(schemaName);
        sb.append(".T031E ");
        sb.append(" SET COMPANY_CODE = ?, TABLE_SUBSET = ?, EFFECTIVE_DATE = ?, POL_INCREASE_CODE = ?, SEX_CODE = ?, UNDER_BASIS_CODE = ?, SPECIAL_CLASS_CODE = ?, MAX_ISSUE_AGE = ?, MAX_DURATION = ?, MAX_ATTAINED_AGE = ?, MAX_COVERAGE_UNITS = ?, NO_LAPSE_IND = ?, FLAT_FEE = ?, CHG_PER_UNIT_COV = ?, PCT_COST_OF_RISK = ?, CONTAGION_FACTOR = ?");
        sb.append(" WHERE COMPANY_CODE = ? AND TABLE_SUBSET = ? AND EFFECTIVE_DATE = ? AND POL_INCREASE_CODE = ? AND SEX_CODE = ? AND UNDER_BASIS_CODE = ? AND SPECIAL_CLASS_CODE = ? AND MAX_ISSUE_AGE = ? AND MAX_DURATION = ? AND MAX_ATTAINED_AGE = ? AND MAX_COVERAGE_UNITS = ? AND NO_LAPSE_IND = ?");
        return sb.toString();
    }
    
    public String prepareDeleteStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("DELETE FROM ").append(schemaName);
        sb.append(".T031E ");
        sb.append(" WHERE COMPANY_CODE = ? AND TABLE_SUBSET = ? AND EFFECTIVE_DATE = ? AND POL_INCREASE_CODE = ? AND SEX_CODE = ? AND UNDER_BASIS_CODE = ? AND SPECIAL_CLASS_CODE = ? AND MAX_ISSUE_AGE = ? AND MAX_DURATION = ? AND MAX_ATTAINED_AGE = ? AND MAX_COVERAGE_UNITS = ? AND NO_LAPSE_IND = ?");
        return sb.toString();
    }
}
