package com.csc.fsg.life.pw.web.io.descriptor.wma;

import com.csc.fsg.life.pw.web.io.*;

public class T047XDescriptor
    extends TableDescriptor
{
    private static final String pagingSql = "SELECT COMPANY_CODE, PRODUCT_PREFIX, PRODUCT_SUFFIX, PLAN_CODE, ISSUE_STATE, LINE_OF_BUSINESS, EFFECTIVE_DATE, CALC_TYPE_IND, SPECIAL_CLASS_CODE, PREMIUM_CLASS_CODE, RATING_FACTOR, ML_LEV_AGE_ADJ_NO, FEM_LEV_AGE_ADJ_NO, ML_LEVMRT_ASMP_TBL, FEM_LVMRT_ASMP_TBL, ML_VAR_AGE_ADJ_NO, FEM_VAR_AGE_ADJ_NO, ML_VARMRT_ASMP_TBL, FEM_VRMRT_ASMP_TBL, ML_PRM_AGE_ADJ_NO, FEM_PRM_AGE_ADJ_NO, ML_PRMMRT_ASMP_TBL, FEM_PRMMRT_ASMP_TBL, GDLN_LEV_INT_TBL, GDLN_SNGL_INT_TBL, GDLN_LEV_ANN_FCT, GDLN_SNGL_ANN_FCT, OFF_ANN_CALC, CALC_ASSUMP_IND, COMMUT_CALC_IND, UNSX_LEV_AGE_ADJ, UNSX_LEV_MORT_ATBL, UNSX_VAR_AGE_ADJ, UNSX_VAR_MORT_ATBL, UNSX_PRM_AGE_ADJ, UNSX_PRM_MORT_ATBL, LEV_ML_LEV_INT_FCT, LEV_FEM_LEVINT_FCT, VAR_ML_LEV_INT_FCT, VAR_FEMLEV_INT_FCT, PRM_ML_LEV_INT_FCT, PRM_FEMLEV_INT_FCT, LEV_ML_SGL_INT_FCT, LEV_FEM_SGLINT_FCT, VAR_ML_SGL_INT_FCT, VAR_FEMSGL_INT_FCT, PRM_ML_SGL_INT_FCT, PRM_FEMSGL_INT_FCT, LEVUNSX_LEV_INTFCT, VARUNSX_LEV_INTFCT, PRMUNSX_LEV_INTFCT, LEVUNSX_SGL_INTFCT, VARUNSX_SGL_INTFCT, PRMUNSX_SGL_INTFCT FROM ";
    
    public void initialize()
    {
        setRowClass(T047XRow.class);
        setTableName("T047X");
        setTableId("047");
        super.initialize();
    }
    
    public void initializeColumnDescriptors()
    {
        super.initializeColumnDescriptors();
        addColumnDescriptor(new ColumnDescriptor(this,"getCompanyCode","setCompanyCode","COMPANY_CODE,1,1,3,0,true|,1,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getProductPrefix","setProductPrefix","PRODUCT_PREFIX,1,2,1,0,true|,2,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getProductSuffix","setProductSuffix","PRODUCT_SUFFIX,1,3,1,0,true|,3,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPlanCode","setPlanCode","PLAN_CODE,1,4,6,0,true|,4,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getIssueState","setIssueState","ISSUE_STATE,1,5,3,0,true|,5,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLineOfBusiness","setLineOfBusiness","LINE_OF_BUSINESS,1,6,3,0,true|,6,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getEffectiveDate","setEffectiveDate","EFFECTIVE_DATE,91,7,10,0,true|,7,DATE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getCalcTypeInd","setCalcTypeInd","CALC_TYPE_IND,1,8,1,0,true|,8,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getSpecialClassCode","setSpecialClassCode","SPECIAL_CLASS_CODE,1,9,2,0,true|,9,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPremiumClassCode","setPremiumClassCode","PREMIUM_CLASS_CODE,1,10,1,0,true|,10,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getRatingFactor","setRatingFactor","RATING_FACTOR,3,11,6,5,true|,11,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMlLevAgeAdjNo","setMlLevAgeAdjNo","ML_LEV_AGE_ADJ_NO,3,12,3,0,false|,16,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFemLevAgeAdjNo","setFemLevAgeAdjNo","FEM_LEV_AGE_ADJ_NO,3,13,3,0,false|,18,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMlLevmrtAsmpTbl","setMlLevmrtAsmpTbl","ML_LEVMRT_ASMP_TBL,1,14,16,0,false|,15,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFemLvmrtAsmpTbl","setFemLvmrtAsmpTbl","FEM_LVMRT_ASMP_TBL,1,15,16,0,false|,17,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMlVarAgeAdjNo","setMlVarAgeAdjNo","ML_VAR_AGE_ADJ_NO,3,16,3,0,false|,22,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFemVarAgeAdjNo","setFemVarAgeAdjNo","FEM_VAR_AGE_ADJ_NO,3,17,3,0,false|,24,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMlVarmrtAsmpTbl","setMlVarmrtAsmpTbl","ML_VARMRT_ASMP_TBL,1,18,16,0,false|,21,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFemVrmrtAsmpTbl","setFemVrmrtAsmpTbl","FEM_VRMRT_ASMP_TBL,1,19,16,0,false|,23,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMlPrmAgeAdjNo","setMlPrmAgeAdjNo","ML_PRM_AGE_ADJ_NO,3,20,3,0,false|,28,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFemPrmAgeAdjNo","setFemPrmAgeAdjNo","FEM_PRM_AGE_ADJ_NO,3,21,3,0,false|,30,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMlPrmmrtAsmpTbl","setMlPrmmrtAsmpTbl","ML_PRMMRT_ASMP_TBL,1,22,16,0,false|,27,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFemPrmmrtAsmpTbl","setFemPrmmrtAsmpTbl","FEM_PRMMRT_ASMP_TBL,1,23,16,0,false|,29,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getGdlnLevIntTbl","setGdlnLevIntTbl","GDLN_LEV_INT_TBL,1,24,16,0,false|,33,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getGdlnSnglIntTbl","setGdlnSnglIntTbl","GDLN_SNGL_INT_TBL,1,25,16,0,false|,35,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getGdlnLevAnnFct","setGdlnLevAnnFct","GDLN_LEV_ANN_FCT,3,26,6,4,false|,34,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getGdlnSnglAnnFct","setGdlnSnglAnnFct","GDLN_SNGL_ANN_FCT,3,27,6,4,false|,36,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getOffAnnCalc","setOffAnnCalc","OFF_ANN_CALC,1,28,1,0,false|,14,CHAR,4,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getCalcAssumpInd","setCalcAssumpInd","CALC_ASSUMP_IND,1,29,1,0,false|,12,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getCommutCalcInd","setCommutCalcInd","COMMUT_CALC_IND,1,30,1,0,false|,13,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnsxLevAgeAdj","setUnsxLevAgeAdj","UNSX_LEV_AGE_ADJ,3,31,3,0,false|,20,INTEGER,4,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnsxLevMortAtbl","setUnsxLevMortAtbl","UNSX_LEV_MORT_ATBL,1,32,16,0,false|,19,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnsxVarAgeAdj","setUnsxVarAgeAdj","UNSX_VAR_AGE_ADJ,3,33,3,0,false|,26,INTEGER,4,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnsxVarMortAtbl","setUnsxVarMortAtbl","UNSX_VAR_MORT_ATBL,1,34,16,0,false|,25,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnsxPrmAgeAdj","setUnsxPrmAgeAdj","UNSX_PRM_AGE_ADJ,3,35,3,0,false|,32,INTEGER,4,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getUnsxPrmMortAtbl","setUnsxPrmMortAtbl","UNSX_PRM_MORT_ATBL,1,36,16,0,false|,31,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLevMlLevIntFct","setLevMlLevIntFct","LEV_ML_LEV_INT_FCT,1,37,16,0,false|,37,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLevFemLevintFct","setLevFemLevintFct","LEV_FEM_LEVINT_FCT,1,38,16,0,false|,38,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getVarMlLevIntFct","setVarMlLevIntFct","VAR_ML_LEV_INT_FCT,1,39,16,0,false|,40,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getVarFemlevIntFct","setVarFemlevIntFct","VAR_FEMLEV_INT_FCT,1,40,16,0,false|,41,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPrmMlLevIntFct","setPrmMlLevIntFct","PRM_ML_LEV_INT_FCT,1,41,16,0,false|,43,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPrmFemlevIntFct","setPrmFemlevIntFct","PRM_FEMLEV_INT_FCT,1,42,16,0,false|,44,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLevMlSglIntFct","setLevMlSglIntFct","LEV_ML_SGL_INT_FCT,1,43,16,0,false|,46,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLevFemSglintFct","setLevFemSglintFct","LEV_FEM_SGLINT_FCT,1,44,16,0,false|,47,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getVarMlSglIntFct","setVarMlSglIntFct","VAR_ML_SGL_INT_FCT,1,45,16,0,false|,49,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getVarFemsglIntFct","setVarFemsglIntFct","VAR_FEMSGL_INT_FCT,1,46,16,0,false|,50,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPrmMlSglIntFct","setPrmMlSglIntFct","PRM_ML_SGL_INT_FCT,1,47,16,0,false|,52,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPrmFemsglIntFct","setPrmFemsglIntFct","PRM_FEMSGL_INT_FCT,1,48,16,0,false|,53,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLevunsxLevIntfct","setLevunsxLevIntfct","LEVUNSX_LEV_INTFCT,1,49,16,0,false|,39,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getVarunsxLevIntfct","setVarunsxLevIntfct","VARUNSX_LEV_INTFCT,1,50,16,0,false|,42,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPrmunsxLevIntfct","setPrmunsxLevIntfct","PRMUNSX_LEV_INTFCT,1,51,16,0,false|,45,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getLevunsxSglIntfct","setLevunsxSglIntfct","LEVUNSX_SGL_INTFCT,1,52,16,0,false|,48,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getVarunsxSglIntfct","setVarunsxSglIntfct","VARUNSX_SGL_INTFCT,1,53,16,0,false|,51,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPrmunsxSglIntfct","setPrmunsxSglIntfct","PRMUNSX_SGL_INTFCT,1,54,16,0,false|,54,CHAR,1,null,null,null,null,null"));
    }
    
    public String getPagingSQL(String schemaName,boolean isSubsetMode,boolean isNext, boolean locator)
    {
        String pagingWhere = null;
        String order = null;
        if (isNext) {
            if (isSubsetMode)
                if (locator)
                    pagingWhere = ".T047X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND ((PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND > :calc_type_ind) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE > :special_class_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR > :rating_factor) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR = :rating_factor)) ";
                else 
                    pagingWhere = ".T047X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND ((PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND > :calc_type_ind) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE > :special_class_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR > :rating_factor)) ";
            else
                if (locator)
                    pagingWhere = ".T047X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX > :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND > :calc_type_ind) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE > :special_class_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR > :rating_factor) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR = :rating_factor)) ";
                else
                    pagingWhere = ".T047X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX > :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX > :product_suffix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE > :plan_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE > :issue_state) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS > :line_of_business) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE > :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND > :calc_type_ind) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE > :special_class_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR > :rating_factor)) ";
            order = " ORDER BY COMPANY_CODE, PRODUCT_PREFIX, PRODUCT_SUFFIX, PLAN_CODE, ISSUE_STATE, LINE_OF_BUSINESS, EFFECTIVE_DATE, CALC_TYPE_IND, SPECIAL_CLASS_CODE, PREMIUM_CLASS_CODE, RATING_FACTOR";
        }
        else {
            if (isSubsetMode)
                pagingWhere = ".T047X WHERE (COMPANY_CODE = :company_code) AND (PRODUCT_PREFIX = :product_prefix) AND ((PRODUCT_SUFFIX < :product_suffix) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE < :plan_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE < :issue_state) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS < :line_of_business) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE < :effective_date) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND < :calc_type_ind) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE < :special_class_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE < :premium_class_code) OR (PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR < :rating_factor)) ";
            else
                pagingWhere = ".T047X WHERE (COMPANY_CODE = :company_code) AND ((PRODUCT_PREFIX < :product_prefix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX < :product_suffix) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE < :plan_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE < :issue_state) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS < :line_of_business) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE < :effective_date) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND < :calc_type_ind) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE < :special_class_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE < :premium_class_code) OR (PRODUCT_PREFIX = :product_prefix AND PRODUCT_SUFFIX = :product_suffix AND PLAN_CODE = :plan_code AND ISSUE_STATE = :issue_state AND LINE_OF_BUSINESS = :line_of_business AND EFFECTIVE_DATE = :effective_date AND CALC_TYPE_IND = :calc_type_ind AND SPECIAL_CLASS_CODE = :special_class_code AND PREMIUM_CLASS_CODE = :premium_class_code AND RATING_FACTOR < :rating_factor)) ";
            order = " ORDER BY COMPANY_CODE DESC, PRODUCT_PREFIX DESC, PRODUCT_SUFFIX DESC, PLAN_CODE DESC, ISSUE_STATE DESC, LINE_OF_BUSINESS DESC, EFFECTIVE_DATE DESC, CALC_TYPE_IND DESC, SPECIAL_CLASS_CODE DESC, PREMIUM_CLASS_CODE DESC, RATING_FACTOR DESC";
        }
        return pagingSql + schemaName + pagingWhere + order;
    }
    
    public String prepareInsertStmt(String schemaName) {
        StringBuffer sb = new StringBuffer();
        sb.append("INSERT INTO ").append(schemaName);
        sb.append(".T047X ( ");
        sb.append("COMPANY_CODE, PRODUCT_PREFIX, PRODUCT_SUFFIX, PLAN_CODE, ISSUE_STATE, LINE_OF_BUSINESS, EFFECTIVE_DATE, CALC_TYPE_IND, SPECIAL_CLASS_CODE, PREMIUM_CLASS_CODE, RATING_FACTOR, ML_LEV_AGE_ADJ_NO, FEM_LEV_AGE_ADJ_NO, ML_LEVMRT_ASMP_TBL, FEM_LVMRT_ASMP_TBL, ML_VAR_AGE_ADJ_NO, FEM_VAR_AGE_ADJ_NO, ML_VARMRT_ASMP_TBL, FEM_VRMRT_ASMP_TBL, ML_PRM_AGE_ADJ_NO, FEM_PRM_AGE_ADJ_NO, ML_PRMMRT_ASMP_TBL, FEM_PRMMRT_ASMP_TBL, GDLN_LEV_INT_TBL, GDLN_SNGL_INT_TBL, GDLN_LEV_ANN_FCT, GDLN_SNGL_ANN_FCT, OFF_ANN_CALC, CALC_ASSUMP_IND, COMMUT_CALC_IND, UNSX_LEV_AGE_ADJ, UNSX_LEV_MORT_ATBL, UNSX_VAR_AGE_ADJ, UNSX_VAR_MORT_ATBL, UNSX_PRM_AGE_ADJ, UNSX_PRM_MORT_ATBL, LEV_ML_LEV_INT_FCT, LEV_FEM_LEVINT_FCT, VAR_ML_LEV_INT_FCT, VAR_FEMLEV_INT_FCT, PRM_ML_LEV_INT_FCT, PRM_FEMLEV_INT_FCT, LEV_ML_SGL_INT_FCT, LEV_FEM_SGLINT_FCT, VAR_ML_SGL_INT_FCT, VAR_FEMSGL_INT_FCT, PRM_ML_SGL_INT_FCT, PRM_FEMSGL_INT_FCT, LEVUNSX_LEV_INTFCT, VARUNSX_LEV_INTFCT, PRMUNSX_LEV_INTFCT, LEVUNSX_SGL_INTFCT, VARUNSX_SGL_INTFCT, PRMUNSX_SGL_INTFCT )");
        sb.append(" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )");
        return sb.toString();
    }
    
    public String prepareUpdateStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("UPDATE ").append(schemaName);
        sb.append(".T047X ");
        sb.append(" SET COMPANY_CODE = ?, PRODUCT_PREFIX = ?, PRODUCT_SUFFIX = ?, PLAN_CODE = ?, ISSUE_STATE = ?, LINE_OF_BUSINESS = ?, EFFECTIVE_DATE = ?, CALC_TYPE_IND = ?, SPECIAL_CLASS_CODE = ?, PREMIUM_CLASS_CODE = ?, RATING_FACTOR = ?, ML_LEV_AGE_ADJ_NO = ?, FEM_LEV_AGE_ADJ_NO = ?, ML_LEVMRT_ASMP_TBL = ?, FEM_LVMRT_ASMP_TBL = ?, ML_VAR_AGE_ADJ_NO = ?, FEM_VAR_AGE_ADJ_NO = ?, ML_VARMRT_ASMP_TBL = ?, FEM_VRMRT_ASMP_TBL = ?, ML_PRM_AGE_ADJ_NO = ?, FEM_PRM_AGE_ADJ_NO = ?, ML_PRMMRT_ASMP_TBL = ?, FEM_PRMMRT_ASMP_TBL = ?, GDLN_LEV_INT_TBL = ?, GDLN_SNGL_INT_TBL = ?, GDLN_LEV_ANN_FCT = ?, GDLN_SNGL_ANN_FCT = ?, OFF_ANN_CALC = ?, CALC_ASSUMP_IND = ?, COMMUT_CALC_IND = ?, UNSX_LEV_AGE_ADJ = ?, UNSX_LEV_MORT_ATBL = ?, UNSX_VAR_AGE_ADJ = ?, UNSX_VAR_MORT_ATBL = ?, UNSX_PRM_AGE_ADJ = ?, UNSX_PRM_MORT_ATBL = ?, LEV_ML_LEV_INT_FCT = ?, LEV_FEM_LEVINT_FCT = ?, VAR_ML_LEV_INT_FCT = ?, VAR_FEMLEV_INT_FCT = ?, PRM_ML_LEV_INT_FCT = ?, PRM_FEMLEV_INT_FCT = ?, LEV_ML_SGL_INT_FCT = ?, LEV_FEM_SGLINT_FCT = ?, VAR_ML_SGL_INT_FCT = ?, VAR_FEMSGL_INT_FCT = ?, PRM_ML_SGL_INT_FCT = ?, PRM_FEMSGL_INT_FCT = ?, LEVUNSX_LEV_INTFCT = ?, VARUNSX_LEV_INTFCT = ?, PRMUNSX_LEV_INTFCT = ?, LEVUNSX_SGL_INTFCT = ?, VARUNSX_SGL_INTFCT = ?, PRMUNSX_SGL_INTFCT = ?");
        sb.append(" WHERE COMPANY_CODE = ? AND PRODUCT_PREFIX = ? AND PRODUCT_SUFFIX = ? AND PLAN_CODE = ? AND ISSUE_STATE = ? AND LINE_OF_BUSINESS = ? AND EFFECTIVE_DATE = ? AND CALC_TYPE_IND = ? AND SPECIAL_CLASS_CODE = ? AND PREMIUM_CLASS_CODE = ? AND RATING_FACTOR = ?");
        return sb.toString();
    }
    
    public String prepareDeleteStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("DELETE FROM ").append(schemaName);
        sb.append(".T047X ");
        sb.append(" WHERE COMPANY_CODE = ? AND PRODUCT_PREFIX = ? AND PRODUCT_SUFFIX = ? AND PLAN_CODE = ? AND ISSUE_STATE = ? AND LINE_OF_BUSINESS = ? AND EFFECTIVE_DATE = ? AND CALC_TYPE_IND = ? AND SPECIAL_CLASS_CODE = ? AND PREMIUM_CLASS_CODE = ? AND RATING_FACTOR = ?");
        return sb.toString();
    }
}
