package com.csc.fsg.life.pw.web.io.descriptor.wma;

import com.csc.fsg.life.pw.web.io.*;

public class TH22HDescriptor
    extends TableDescriptor
{
    private static final String pagingSql = "SELECT COMPANY_CODE, TABLE_SUBSET, EFFECTIVE_DATE, SEX_CODE, PREMIUM_CLASS_CODE, MAX_POLICY_DUR, MAX_RIDER_ISS_AGE, MAX_RIDER_DUR, MAX_RIDER_ATTD_AGE, CURR_VALUE_AMOUNT, CURR_VALUE_UNITS, MEMO_CODE, FLAT_CHRG_AMOUNT, FLAT_CHRG_PERCENT FROM ";
    
    public void initialize()
    {
        setRowClass(TH22HRow.class);
        setTableName("TH22H");
        setTableId("H22");
        super.initialize();
    }
    
    public void initializeColumnDescriptors()
    {
        super.initializeColumnDescriptors();
        addColumnDescriptor(new ColumnDescriptor(this,"getCompanyCode","setCompanyCode","COMPANY_CODE,1,1,3,0,true|,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getTableSubset","setTableSubset","TABLE_SUBSET,1,2,16,0,true|,0,CHAR,1,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getEffectiveDate","setEffectiveDate","EFFECTIVE_DATE,91,3,10,0,true|,0,DATE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getSexCode","setSexCode","SEX_CODE,1,4,1,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getPremiumClassCode","setPremiumClassCode","PREMIUM_CLASS_CODE,1,5,1,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxPolicyDur","setMaxPolicyDur","MAX_POLICY_DUR,3,6,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxRiderIssAge","setMaxRiderIssAge","MAX_RIDER_ISS_AGE,3,7,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxRiderDur","setMaxRiderDur","MAX_RIDER_DUR,3,8,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMaxRiderAttdAge","setMaxRiderAttdAge","MAX_RIDER_ATTD_AGE,3,9,3,0,true|,0,INTEGER,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getCurrValueAmount","setCurrValueAmount","CURR_VALUE_AMOUNT,3,10,11,2,true|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getCurrValueUnits","setCurrValueUnits","CURR_VALUE_UNITS,3,11,11,5,true|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getMemoCode","setMemoCode","MEMO_CODE,1,12,2,0,true|,0,CHAR,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFlatChrgAmount","setFlatChrgAmount","FLAT_CHRG_AMOUNT,3,13,7,2,false|,0,DOUBLE,0,null,null,null,null,null"));
        addColumnDescriptor(new ColumnDescriptor(this,"getFlatChrgPercent","setFlatChrgPercent","FLAT_CHRG_PERCENT,3,14,5,2,false|,0,DOUBLE,0,null,null,null,null,null"));
    }
    
    public String getPagingSQL(String schemaName,boolean isSubsetMode,boolean isNext, boolean locator)
    {
        String pagingWhere = null;
        String order = null;
        if (isNext) {
            if (isSubsetMode)
                if (locator)
                    pagingWhere = ".TH22H WHERE (COMPANY_CODE = :company_code) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE > :effective_date) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR > :max_policy_dur) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE > :max_rider_iss_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR > :max_rider_dur) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE > :max_rider_attd_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT > :curr_value_amount) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS > :curr_value_units) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE > :memo_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE = :memo_code)) ";
                else 
                    pagingWhere = ".TH22H WHERE (COMPANY_CODE = :company_code) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE > :effective_date) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR > :max_policy_dur) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE > :max_rider_iss_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR > :max_rider_dur) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE > :max_rider_attd_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT > :curr_value_amount) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS > :curr_value_units) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE > :memo_code)) ";
            else
                if (locator)
                    pagingWhere = ".TH22H WHERE (COMPANY_CODE = :company_code) AND ((TABLE_SUBSET > :table_subset) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE > :effective_date) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR > :max_policy_dur) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE > :max_rider_iss_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR > :max_rider_dur) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE > :max_rider_attd_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT > :curr_value_amount) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS > :curr_value_units) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE > :memo_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE = :memo_code)) ";
                else
                    pagingWhere = ".TH22H WHERE (COMPANY_CODE = :company_code) AND ((TABLE_SUBSET > :table_subset) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE > :effective_date) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE > :sex_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE > :premium_class_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR > :max_policy_dur) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE > :max_rider_iss_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR > :max_rider_dur) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE > :max_rider_attd_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT > :curr_value_amount) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS > :curr_value_units) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE > :memo_code)) ";
            order = " ORDER BY COMPANY_CODE, TABLE_SUBSET, EFFECTIVE_DATE, SEX_CODE, PREMIUM_CLASS_CODE, MAX_POLICY_DUR, MAX_RIDER_ISS_AGE, MAX_RIDER_DUR, MAX_RIDER_ATTD_AGE, CURR_VALUE_AMOUNT, CURR_VALUE_UNITS, MEMO_CODE";
        }
        else {
            if (isSubsetMode)
                pagingWhere = ".TH22H WHERE (COMPANY_CODE = :company_code) AND (TABLE_SUBSET = :table_subset) AND ((EFFECTIVE_DATE < :effective_date) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE < :sex_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE < :premium_class_code) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR < :max_policy_dur) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE < :max_rider_iss_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR < :max_rider_dur) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE < :max_rider_attd_age) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT < :curr_value_amount) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS < :curr_value_units) OR (EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE < :memo_code)) ";
            else
                pagingWhere = ".TH22H WHERE (COMPANY_CODE = :company_code) AND ((TABLE_SUBSET < :table_subset) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE < :effective_date) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE < :sex_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE < :premium_class_code) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR < :max_policy_dur) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE < :max_rider_iss_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR < :max_rider_dur) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE < :max_rider_attd_age) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT < :curr_value_amount) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS < :curr_value_units) OR (TABLE_SUBSET = :table_subset AND EFFECTIVE_DATE = :effective_date AND SEX_CODE = :sex_code AND PREMIUM_CLASS_CODE = :premium_class_code AND MAX_POLICY_DUR = :max_policy_dur AND MAX_RIDER_ISS_AGE = :max_rider_iss_age AND MAX_RIDER_DUR = :max_rider_dur AND MAX_RIDER_ATTD_AGE = :max_rider_attd_age AND CURR_VALUE_AMOUNT = :curr_value_amount AND CURR_VALUE_UNITS = :curr_value_units AND MEMO_CODE < :memo_code)) ";
            order = " ORDER BY COMPANY_CODE DESC, TABLE_SUBSET DESC, EFFECTIVE_DATE DESC, SEX_CODE DESC, PREMIUM_CLASS_CODE DESC, MAX_POLICY_DUR DESC, MAX_RIDER_ISS_AGE DESC, MAX_RIDER_DUR DESC, MAX_RIDER_ATTD_AGE DESC, CURR_VALUE_AMOUNT DESC, CURR_VALUE_UNITS DESC, MEMO_CODE DESC";
        }
        return pagingSql + schemaName + pagingWhere + order;
    }
    
    public String prepareInsertStmt(String schemaName) {
        StringBuffer sb = new StringBuffer();
        sb.append("INSERT INTO ").append(schemaName);
        sb.append(".TH22H ( ");
        sb.append("COMPANY_CODE, TABLE_SUBSET, EFFECTIVE_DATE, SEX_CODE, PREMIUM_CLASS_CODE, MAX_POLICY_DUR, MAX_RIDER_ISS_AGE, MAX_RIDER_DUR, MAX_RIDER_ATTD_AGE, CURR_VALUE_AMOUNT, CURR_VALUE_UNITS, MEMO_CODE, FLAT_CHRG_AMOUNT, FLAT_CHRG_PERCENT )");
        sb.append(" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )");
        return sb.toString();
    }
    
    public String prepareUpdateStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("UPDATE ").append(schemaName);
        sb.append(".TH22H ");
        sb.append(" SET COMPANY_CODE = ?, TABLE_SUBSET = ?, EFFECTIVE_DATE = ?, SEX_CODE = ?, PREMIUM_CLASS_CODE = ?, MAX_POLICY_DUR = ?, MAX_RIDER_ISS_AGE = ?, MAX_RIDER_DUR = ?, MAX_RIDER_ATTD_AGE = ?, CURR_VALUE_AMOUNT = ?, CURR_VALUE_UNITS = ?, MEMO_CODE = ?, FLAT_CHRG_AMOUNT = ?, FLAT_CHRG_PERCENT = ?");
        sb.append(" WHERE COMPANY_CODE = ? AND TABLE_SUBSET = ? AND EFFECTIVE_DATE = ? AND SEX_CODE = ? AND PREMIUM_CLASS_CODE = ? AND MAX_POLICY_DUR = ? AND MAX_RIDER_ISS_AGE = ? AND MAX_RIDER_DUR = ? AND MAX_RIDER_ATTD_AGE = ? AND CURR_VALUE_AMOUNT = ? AND CURR_VALUE_UNITS = ? AND MEMO_CODE = ?");
        return sb.toString();
    }
    
    public String prepareDeleteStmt(String schemaName)
    {
        StringBuffer sb = new StringBuffer();
        sb.append("DELETE FROM ").append(schemaName);
        sb.append(".TH22H ");
        sb.append(" WHERE COMPANY_CODE = ? AND TABLE_SUBSET = ? AND EFFECTIVE_DATE = ? AND SEX_CODE = ? AND PREMIUM_CLASS_CODE = ? AND MAX_POLICY_DUR = ? AND MAX_RIDER_ISS_AGE = ? AND MAX_RIDER_DUR = ? AND MAX_RIDER_ATTD_AGE = ? AND CURR_VALUE_AMOUNT = ? AND CURR_VALUE_UNITS = ? AND MEMO_CODE = ?");
        return sb.toString();
    }
}
