# Product Wizard REST API
swagger: '2.0'

info:
  title: Product Wizard Business Rule Tree API
  description: Business Rule Tree REST API for Product Wizard
  version: "0.0.1"

host: localhost:8443

schemes:
  - https

basePath: /ng-pw-rest

paths:
  /business-rule-tree/core:
    get:
      summary: |
        Retrieves information required to populate
        the core part of Business Rule Tree.
      description: |
        This endpoint returns information, which can be used
        to populate the core part of Business Rule Tree.
      produces:
        - application/json
      operationId: getBusinessRuleTreeCore
      parameters:
        - name: authToken
          in: header
          description: |
            Auth Token.
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment Id.
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code.
          required: true
          type: string
        - name: productCode
          in: header
          description: |
            Product Code.
          required: true
          type: string
        - name: includeOrphans
          in: header
          description: |
            Indicator used to request inclusion
            of orphan subsets in the returned data.
          required: false
          type: boolean
      tags:
        - Business Rule Tree
      responses:
        200:
          description: |
            OK.  The data model corresponding to the core part
            of Business Rule Tree is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/treeNode'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema:
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Auth token is either missing or invalid.
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the required resources.
        default:
          description: Unexpected Error.
          schema:
            $ref: '#/definitions/errorModel'

  /business-rule-tree/common/tables:
    get:
      summary: |
        Retrieves information required to populate
        the Common Table subtree of Business Rule Tree.
      description: |
        This endpoint returns information, which can be used
        to populate the Common Table subtree of Business
        Rule Tree.
      produces:
        - application/json
      operationId: getBusinessRuleTreeCommonTables
      parameters:
        - name: authToken
          in: header
          description: |
            Auth Token.
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment Id.
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code.
          required: true
          type: string
        - name: viewChanges
          in: header
          description: |
            Indicator used to request Rules or Rules with Changes.
          required: false
          type: boolean
      tags:
        - Business Rule Tree
      responses:
        200:
          description: |
            OK.  The data model corresponding to the Common Table
            subtree of Business Rule Tree is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/treeNode'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema:
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Auth token is either missing or invalid.
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the required resources.
        default:
          description: Unexpected Error.
          schema:
            $ref: '#/definitions/errorModel'

  /business-rule-tree/plan/list:
    get:
      summary: |
        Retrieves a list of plans matching the provided criteria.
      description: |
        This endpoint returns a list of Business Rule Tree nodes,
        containing information about the plans matching
        the provided criteria.
      produces:
        - application/json
      operationId: getBusinessRuleTreePlanList
      parameters:
        - name: authToken
          in: header
          description: |
            Auth Token.
          required: true
          type: string
        - name: lazyType
          in: header
          description: |
            Indicates the lazy-loading type of the node,
            to which the returned plan nodes are to be attached.
            The allowed values match those in enum treeNodeLazyType.
            Due to Swagger's limitations, treeNodeLazyType
            cannot be referenced here directly.
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment Id.
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code.
          required: true
          type: string
        - name: productCode
          in: header
          description: |
            Product Code.
          required: true
          type: string
        - name: planCode
          in: header
          description: |
            Plan Code.
          required: false
          type: string
        - name: issueState
          in: header
          description: |
            Issue State.
          required: false
          type: string
        - name: lob
          in: header
          description: |
            Line of Business.
          required: false
          type: string
        - name: effDate
          in: header
          description: |
            Effective Date.
          required: false
          type: string
        - name: viewChanges
          in: header
          description: |
            Indicator used to request Rules or Rules with Changes.
          required: false
          type: boolean
        - name: includeOrphans
          in: header
          description: |
            Indicator used to request inclusion
            of orphan subsets in the returned data.
          required: false
          type: boolean
      tags:
        - Business Rule Tree
      responses:
        200:
          description: |
            OK.  The data model corresponding to the list
            of plans matching the provided criteria is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/treeNode'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema:
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Auth token is either missing or invalid.
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the required resources.
        default:
          description: Unexpected Error.
          schema:
            $ref: '#/definitions/errorModel'

  /business-rule-tree/plan/detail:
    post:
      summary: |
        Retrieves detailed information about a plan.
      description: |
        This endpoint returns detailed information about a plan
        indicated by the provided key information.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: getBusinessRuleTreePlanDetails
      parameters:
        - name: authToken
          in: header
          description: |
            Auth Token.
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment Id.
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code.
          required: true
          type: string
        - name: planKey
          in: body
          description: |
            Key information required to retrieve plan information.
          required: true
          schema:
            $ref: '#/definitions/treeNodePlanKey'
        - name: viewChanges
          in: header
          description: |
            Indicator used to request Rules or Rules with Changes.
          required: false
          type: boolean
      tags:
        - Business Rule Tree
      responses:
        200:
          description: |
            OK.  The data model corresponding to the selected
            plan is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/treeNode'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema:
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Auth token is either missing or invalid.
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the required resources.
        default:
          description: Unexpected Error.
          schema:
            $ref: '#/definitions/errorModel'

  /business-rule-tree/orphans:
    get:
      summary: |
        Retrieves a list of orphan subsets matching
        the provided criteria.
      description: |
        This endpoint returns a list of orphan subset
        nodes matching the provided criteria.
      produces:
        - application/json
      operationId: getBusinessRuleTreeOrphanSubsets
      parameters:
        - name: authToken
          in: header
          description: |
            Auth Token.
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment Id.
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code.
          required: true
          type: string
        - name: productCode
          in: header
          description: |
            Product Code.
          required: true
          type: string
        - name: planCode
          in: header
          description: |
            Plan Code.
          required: false
          type: string
        - name: issueState
          in: header
          description: |
            Issue State.
          required: false
          type: string
        - name: lob
          in: header
          description: |
            Line of Business.
          required: false
          type: string
        - name: effDate
          in: header
          description: |
            Effective Date.
          required: false
          type: string
        - name: viewChanges
          in: header
          description: |
            Indicator used to request Rules or Rules with Changes.
          required: false
          type: boolean
      tags:
        - Business Rule Tree
      responses:
        200:
          description: |
            OK.  The data model corresponding to the list
            of orphan subsets matching the provided criteria
            is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/treeNode'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema:
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Auth token is either missing or invalid.
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the required resources.
        default:
          description: Unexpected Error.
          schema:
            $ref: '#/definitions/errorModel'

definitions:
  treeNode:
    type: object
    required:
      - type
      - label
    properties:
      type:
        type: string
        enum:
          - D   # DISPLAY
          - PA  # PACKAGE
          - PR  # PROJECT
          - C   # COMPANY
          - AF  # ANNUITIY_FOLDER
          - UF  # UNIV_LIFE_FOLDER
          - TF  # TRADITIONAL_FOLDER
          - CTF # COMMON_TABLE_FOLDER
          - PF  # PLAN_FOLDER
          - RF  # RIDER_FOLDER
          - P   # PLAN
          - R   # RIDER
          - T   # TABLE
          - CT  # COMMON_TABLE
          - TS  # TABLE_SUBSET
          - PDF # PDFPLAN_FOLDER
          - OF  # ORPHAN_FOLDER
          - CF  # COMMON_FOLDER
          - OTS # ORPHAN_TABLE_SUBSET
          - PP  # PAYOUT_PLAN
          - PPF # PAYOUTPLAN_FOLDER
          - OG  # ORPHAN_GROUP
      label:
        type: string
      styleClass:
        type: string
      icon:
        type: string
      expandedIcon:
        type: string
      collapsedIcon:
        type: string
      leaf:
        type: boolean
      expanded:
        type: boolean
      data:
        $ref: '#/definitions/treeNodeData'
      children:
        type: array
        items:
          $ref: '#/definitions/treeNode'

  treeNodeData:
    type: object
    properties:
      lazyNode:
        type: boolean
      lazyType:
        type: string
        enum:
          - C   # COMMON
          - PDF # PDF_PLANS
          - H   # COMMON_COVERAGE
          - B   # BASE_PLANS
          - R   # RIDER_PLANS
          - P   # PAYOUT_PLANS
          - O   # ORPHAN_SUBSETS
      name:
        type: string
      tableId:
        type: string
      tableName:
        type: string
      projectName:
        type: string
      packageId:
        type: string
      planKey:
        $ref: '#/definitions/treeNodePlanKey'
      attributes:
        $ref: '#/definitions/treeNodeAttributes'

  treeNodePlanKey:
    type: object
    properties:
      productPrefix:
        type: string
      productSuffix:
        type: string
      planCode:
        type: string
      issueState:
        type: string
      lob:
        type: string
      effDate:
        type: string
        format: date
      planType:
        type: string
      tablePtrId:
        type: string
      tablePtrVar:
        type: string
      tablePtrSubset:
        type: string

  treeNodeAttributes:
    type: object
    properties:
      disabled:
        type: boolean
      updateAllowed:
        type: boolean

# ========================================================
# Common definitions, which begin at this point,
# must exactly match those in the basic API specification.
# ========================================================
  errorModel:
    type: object
    required:
      - severity
      - errorCode
      - message
    properties:
      severity:
        type: string
        enum:
          - ERROR
          - WARNING
      errorCode:
        type: string
      message:
        type: string
