# Product Wizard REST API
swagger: '2.0'

info:
  title: Product Wizard Business Rule Tree API
  description: Business Rule Tree REST API for Product Wizard
  version: "0.0.1"

host: localhost:8443

schemes:
  - https

basePath: /ng-pw-rest

paths:
  /business-rule-tree/search:
    get:
      summary: |
        Retrieve information comprising the Business Rule tree
        with contents matching the provided key values.
      description: |
        This endpoint returns information, which can be used to
        construct display of the Business Rule tree, with contents
        matching the provided key values.
      produces:
        - application/json
      operationId: getBusinessRuleTree
      parameters:
        - name: authToken
          in: header
          description: | 
            Auth Token.
          required: true
          type: string
        - name: viewChanges
          in: header
          description: |
            Indicator used to request Rules or Rules with changes.  
          required: true
          type: boolean
        - name: envId
          in: header
          description: |
            Environment Id. 
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code.
          required: true
          type: string
        - name: productCode
          in: header
          description: |
            Product Code.
          required: true
          type: string
        - name: planCode
          in: header
          description: |
            Plan Code.
          required: false
          type: string
        - name: issueState
          in: header
          description: |
            Issue State.
          required: false
          type: string
        - name: lob
          in: header
          description: |
            Line of Business.
          required: false
          type: string
        - name: effDate
          in: header
          description: |
            Effective Date.
          required: false
          type: string
        - name: includeOrphans
          in: header
          description: |
            Indicator used to request inclusion
            of orphan subsets in the returned data.  
          required: false
          type: boolean
      tags:
        - Business Rule Tree
      responses:
        200:
          description: |
            OK.  The Business Rule tree data model is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/treeNode'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema: 
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Auth token is either missing or invalid. 
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the required resources.
        default:
          description: Unexpected Error.
          schema: 
            $ref: '#/definitions/errorModel'

definitions:
  treeNode:
    type: object
    properties:
      type:
        type: string
        enum:
          - D   # DISPLAY
          - PA  # PACKAGE
          - PR  # PROJECT
          - C   # COMPANY
          - AF  # ANNUITIY_FOLDER
          - UF  # UNIV_LIFE_FOLDER
          - TF  # TRADITIONAL_FOLDER
          - CTF # COMMON_TABLE_FOLDER
          - PF  # PLAN_FOLDER
          - RF  # RIDER_FOLDER
          - P   # PLAN
          - R   # RIDER
          - T   # TABLE
          - CT  # COMMON_TABLE
          - TS  # TABLE_SUBSET
          - PDF # PDFPLAN_FOLDER
          - OF  # ORPHAN_FOLDER
          - CF  # COMMON_FOLDER
          - OTS # ORPHAN_TABLE_SUBSET
          - PP  # PAYOUT_PLAN
          - PPF # PAYOUTPLAN_FOLDER
          - OG  # ORPHAN_GROUP
      label:
        type: string
      styleClass:
        type: string
      icon:
        type: string
      expandedIcon:
        type: string
      collapsedIcon:
        type: string
      leaf:
        type: boolean
      expanded:
        type: boolean
      data:
        $ref: '#/definitions/treeNodeData'
      children:
        type: array
        items:
          $ref: '#/definitions/treeNode'

  treeNodeData:
    type: object
    properties:
      name:
        type: string
      tableId:
        type: string
      projectName:
        type: string
      packageId:
        type: string
      planKey:
        $ref: '#/definitions/treeNodePlanKey'
      attributes:
        $ref: '#/definitions/treeNodeAttributes'

  treeNodePlanKey:
    type: object
    properties:
      productPrefix:
        type: string
      productSuffix:
        type: string
      planCode:
        type: string
      issueState:
        type: string
      lob:
        type: string
      effDate:
        type: string
        format: date
      planType:
        type: string
      tablePtrId:
        type: string
      tablePtrVar:
        type: string
      tablePtrSubset:
        type: string

  treeNodeAttributes:
    type: object
    properties:
      disabled:
        type: boolean
      inquiryAllowed:
        type: boolean
      updateAllowed:
        type: boolean

# ========================================================
# Common definitions, which begin at this point,
# must exactly match those in the basic API specification.
# ========================================================
  errorModel:
    type: object
    properties:
      severity:
        type: string
        enum:
          - ERROR
          - WARNING
      errorCode:
        type: string
      message:
        type: string
