# NG Product Wizard REST API
swagger: '2.0'

info:
  title: NG Product Wizard API
  description: REST API for NG Product Wizard
  version: "0.0.1"

host: localhost:8443

schemes:
  - https

basePath: /ng-pw-rest

paths:
  /security/authentication:
    post:
      summary: Authenticate a user
      description: |
        This endpoint is used to authenticate a user,
        and return the corresponding session token.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: authenticate
      parameters:
        - name: credentials
          in: body
          description: |
            Credentials required to authenticate a user
          required: true
          schema: 
            $ref: '#/definitions/credentials'
      tags:
        - Security
      responses:
        200:
          description: |
            OK.  Authentication completed successfully.  A token
            used to link service requests to the corresponding security
            session, is returned.
          schema:
            $ref: '#/definitions/sessionToken'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /security/logout:
    post:
      summary: Logout a user 
      description: |
        This endpoint is used to terminate the session corresponding to
        the provided token, thus logging out the user, who created the session. 
      produces:
        - application/json
      operationId: logout
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
      tags:
        - Security
      responses:
        200:
          description: |
            OK.  Logout has been successfully completed, and
            the corresponding security session has been invalidated. 
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/environment:
    get:
      summary: Retrieve a list of Environments
      description: |
        This endpoint returns a list of Environments configured in
        the Product Wizard installation, which the authenticated user
        is authorized to access. 
      produces:
        - application/json
      operationId: getEnvironments
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
      tags:
        - Search
      responses:
        200:
          description: |
            OK.  The list of Environments has been
            successfully retrieved.
          schema:
            type: array
            items:
              $ref: '#/definitions/commonSelectItem'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema: 
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        403:
          description: |
            Forbidden.  The user is not authorized to access
            any of the configured environments.
        404:
          description: |
            Not Found.  No configured environments have been found. 
          schema: 
            $ref: '#/definitions/errorModel'
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/common:
    post:
      summary: Search for common plan key information.
      description: |
        This endpoint is used to search for common plan key information,
        which includes key values of type string.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: getPlanCommonValues
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
        - name: searchInput
          in: body
          description: |
            Container with search input parameters.
          required: true
          schema: 
            $ref: '#/definitions/planSearchInput'
      tags:
        - Search
      responses:
        200:
          description: |
            OK.  The requested plan information has been
            successfully retrieved.
          schema:
            type: array
            items:
              $ref: '#/definitions/commonSelectItem'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema: 
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        403:
          description: |
            Forbidden.  The user is not authorized to access
            any of the configured environments and/or companies.
        404:
          description: |
            Not Found.  No data found matching the provided plan key values. 
          schema: 
            $ref: '#/definitions/errorModel'
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/date:
    post:
      summary: Search for plan key information of type date.
      description: |
        This endpoint is used to search for plan key information,
        which includes key values of type date.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: getPlanDateValues
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
        - name: searchInput
          in: body
          description: |
            Container with search input parameters.
          required: true
          schema: 
            $ref: '#/definitions/planSearchInput'
      tags:
        - Search
      responses:
        200:
          description: |
            OK.  The requested plan information has been
            successfully retrieved.
          schema:
            type: array
            items:
              $ref: '#/definitions/dateSelectItem'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema: 
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        403:
          description: |
            Forbidden.  The user is not authorized to access
            any of the configured environments and/or companies.
        404:
          description: |
            Not Found.  No data found matching the provided plan key values. 
          schema: 
            $ref: '#/definitions/errorModel'
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/project:
    get:
      summary: Search for projects.
      description: |
        This endpoint is used to search for projects existing
        in the indicated environment.
      produces:
        - application/json
      operationId: getProjects
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment code
          required: true
          type: string
      tags:
        - Search
      responses:
        200:
          description: |
            OK.  The requested list of projects has been
            successfully retrieved.
          schema:
            type: array
            items:
              type: string
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema: 
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the indicated environment.
        404:
          description: |
            Not Found.  No projects found matching the provided key values. 
          schema: 
            $ref: '#/definitions/errorModel'
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/table:
    get:
      summary: Search for business rule tables.
      description: |
        This endpoint is used to search for
        business rule tables.
      produces:
        - application/json
      operationId: getTables
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
        - name: envId
          in: header
          description: |
            Environment
          required: true
          type: string
        - name: companyCode
          in: header
          description: |
            Company Code
          required: true
          type: string
      tags:
        - Search
      responses:
        200:
          description: |
            OK.  The requested list of business rule
            tables projects has been successfully retrieved.
          schema:
            type: array
            items:
              $ref: '#/definitions/commonSelectItem'
        400:
          description: |
            Bad Request.  Invalid or malformed request detected.
          schema: 
            $ref: '#/definitions/errorModel'
        401:
          description: |
            Unauthorized.  Required authorization information not found.
            Session token is either missing or invalid. 
        403:
          description: |
            Forbidden.  The user is not authorized to access
            the indicated environment or company.
        404:
          description: |
            Not Found.  No business rule tables found matching
            the provided key values. 
          schema: 
            $ref: '#/definitions/errorModel'
        default:
          description: Unexpected Error
          schema:
            type: array
            items:
              $ref: '#/definitions/commonSelectItem'

definitions:
  credentials:
    type: object
    properties:
      userName:
        type: string
        description: Unique identification of a user
      password:
        type: string
        description: Password

  sessionToken:
    type: string
    properties:
      tokenId:
        type: string
        description: A token used to link service requests to the corresponding security session. 

  planSearchInput:
    type: object
    properties:
      mergedView:
        type: boolean
      envId:
        type: string
      companyCode:
        type: string
      productCode:
        type: string
      planCode:
        type: string
      issueState:
        type: string
      lob:
        type: string
      effDate:
        type: string
        format: date

  commonSelectItem:
    type: object
    properties:
      coreValue:
        type: string
        description: The internal representation of value of this item.
      displayValue:
        type: string
        description: Representation of value of this item suitable for display.

  dateSelectItem:
    type: object
    properties:
      coreValue:
        type: string
        format: date
        description: The internal representation of value of this item.
      displayValue:
        type: string
        description: Representation of value of this item suitable for display.

  errorModel:
    type: object
    properties:
      severity:
        type: string
        enum:
          - ERROR
          - WARNING
      errorCode:
        type: string
      message:
        type: string
      fields:
        type: array
        items:
          type: string
