# NG Product Wizard REST API
swagger: '2.0'

info:
  title: NG Product Wizard API
  description: REST API for NG Product Wizard
  version: "0.0.1"

host: localhost:8443

schemes:
  - https

basePath: /ng-pw-rest

paths:
  /security/authentication:
    post:
      summary: Authenticate a user
      description: |
        This endpoint is used to authenticate a user,
        and return the corresponding session token.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: authenticate
      parameters:
        - name: credentials
          in: body
          description: |
            Credentials required to authenticate a user
          required: true
          schema: 
            $ref: '#/definitions/credentials'
      tags:
        - Security
      responses:
        200:
          description: |
            A token used to link service requests to
            the corresponding security session.
          schema:
            $ref: '#/definitions/sessionToken'
        401:
          description: Unauthorized
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /security/logout:
    post:
      summary: Logout a user 
      description: |
        This endpoint is used to terminate the session corresponding to
        the provided token, thus logging out the user, who created the session. 
      produces:
        - application/json
      operationId: logout
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
      tags:
        - Security
      responses:
        200:
          description: Logout successfully completed
        401:
          description: Unauthorized
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/environment:
    get:
      summary: Retrieve a list of Environments
      description: |
        This endpoint returns a list of Environments configured in
        the Product Wizard installation, which the authenticated user
        is authorized to access. 
      produces:
        - application/json
      operationId: searchEnvironments
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
      tags:
        - Search
      responses:
        200:
          description: A list of Environments
          schema:
            type: array
            items:
              $ref: '#/definitions/commonSelectItem'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/common:
    post:
      summary: Search for common plan key information.
      description: |
        This endpoint is used to search for common plan key information,
        which includes key values of type string.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: searchCommonValues
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
        - name: searchInput
          in: body
          description: |
            Container with search input parameters.
          required: true
          schema: 
            $ref: '#/definitions/planSearchInput'
      tags:
        - Search
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              $ref: '#/definitions/commonSelectItem'
        401:
          description: Unauthorized
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /search/date:
    post:
      summary: Search for plan key information of type date.
      description: |
        This endpoint is used to search for plan key information,
        which includes key values of type date.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: searchDateValues
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
        - name: searchInput
          in: body
          description: |
            Container with search input parameters.
          required: true
          schema: 
            $ref: '#/definitions/planSearchInput'
      tags:
        - Search
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              $ref: '#/definitions/dateSelectItem'
        401:
          description: Unauthorized
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

definitions:
  credentials:
    type: object
    properties:
      userName:
        type: string
        description: Unique identification of a user
      password:
        type: string
        description: Password

  sessionToken:
    type: string
    properties:
      tokenId:
        type: string
        description: A token used to link service requests to the corresponding security session. 

  planSearchInput:
    type: object
    properties:
      mergedView:
        type: boolean
      environment:
        type: string
      companyCode:
        type: string
      productCode:
        type: string
      planCode:
        type: string
      issueState:
        type: string
      lob:
        type: string
      effDate:
        type: string
        format: date

  commonSelectItem:
    type: object
    properties:
      coreValue:
        type: string
        description: The internal representation of value of this item.
      displayValue:
        type: string
        description: Representation of value of this item suitable for display.

  dateSelectItem:
    type: object
    properties:
      coreValue:
        type: string
        format: date
        description: The internal representation of value of this item.
      displayValue:
        type: string
        description: Representation of value of this item suitable for display.

  errorModel:
    type: object
    properties:
      severity:
        type: string
        enum:
          - ERROR
          - WARNING
      errorCode:
        type: string
      message:
        type: string
      fields:
        type: array
        items:
          type: string
