# NG Product Wizard REST API
swagger: '2.0'

info:
  title: NG Product Wizard API
  description: REST API for NG Product Wizard
  version: "0.0.1"

host: localhost:8443

schemes:
  - https

basePath: /ng-pw-rest

paths:
  /security/authentication:
    post:
      summary: Authenticate a user
      description: |
        This endpoint will accept user's credentials, then authenticate
        the user, and return the corresponding session token.
      consumes:
        - application/json
      produces:
        - application/json
      operationId: authenticate
      parameters:
        - name: credentials
          in: body
          description: |
            Credentials required to authenticate a user
          required: true
          schema: 
            $ref: '#/definitions/credentials'
      tags:
        - Security
      responses:
        200:
          description: |
            A token used to link service requests to
            the corresponding security session.
          schema:
            $ref: '#/definitions/sessionToken'
        401:
          description: Unauthorized
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

  /security/logout:
    post:
      summary: Logout the current user 
      description: |
        Logout the current user by terminating the session indicated
        by the provided token. 
      produces:
        - application/json
      operationId: logout
      parameters:
        - name: sessionToken
          in: header
          description: | 
            Session Token
          required: true
          type: string
      tags:
        - Security
      responses:
        200:
          description: Logoff successfully completed
        401:
          description: Unauthorized
        default:
          description: Unexpected Error
          schema: 
            $ref: '#/definitions/errorModel'

definitions:
  credentials:
    type: object
    properties:
      userName:
        type: string
        description: Unique identification of a user
      password:
        type: string
        description: Password

  sessionToken:
    type: string
    properties:
      tokenId:
        type: string
        description: A token used to link service requests to the corresponding security session. 

  errorModel:
    type: object
    properties:
      severity:
        type: string
        enum:
          - ERROR
          - WARNING
      errorCode:
        type: string
      message:
        type: string
      fields:
        type: array
        items:
          type: string
